version: '3'

networks:
  ldsp_tier:
    driver: bridge

services:
  ldsp_web:
    container_name: ldsp
    build:
      context: .
      dockerfile: Dockerfile
    command: ./deployment/start-app
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:20007:8001"
    networks:
      - ldsp_tier
